# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guessing_game.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(688, 514)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mapWidget = QtWidgets.QLabel(self.centralwidget)
        self.mapWidget.setGeometry(QtCore.QRect(40, 50, 611, 371))
        self.mapWidget.setText("")
        self.mapWidget.setObjectName("mapWidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(230, 10, 211, 31))
        self.titleLabel.setStyleSheet("font: 20pt \"Segoe Script\";\n"
"color: rgb(144, 0, 216);\n"
"background-color: rgb(219, 212, 255);")
        self.titleLabel.setObjectName("titleLabel")
        self.answerField = QtWidgets.QLineEdit(self.centralwidget)
        self.answerField.setGeometry(QtCore.QRect(10, 470, 591, 21))
        self.answerField.setObjectName("answerField")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 440, 311, 16))
        self.label.setStyleSheet("font: 14pt \"Segoe Script\";\n"
"color: rgb(148, 0, 222);")
        self.label.setObjectName("label")
        self.answerButton = QtWidgets.QPushButton(self.centralwidget)
        self.answerButton.setGeometry(QtCore.QRect(607, 470, 75, 23))
        self.answerButton.setStyleSheet("font: 8pt \"Segoe Script\";\n"
"color: rgb(144, 0, 216);\n"
"background-color: rgb(219, 212, 255);")
        self.answerButton.setObjectName("answerButton")
        self.scoreWidget = QtWidgets.QLCDNumber(self.centralwidget)
        self.scoreWidget.setGeometry(QtCore.QRect(603, 10, 81, 31))
        self.scoreWidget.setStyleSheet("color: rgb(151, 0, 227);")
        self.scoreWidget.setObjectName("scoreWidget")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(550, 10, 41, 31))
        self.nextButton.setStyleSheet("font: 20pt \"Segoe Script\";\n"
"color: rgb(144, 0, 216);\n"
"background-color: rgb(219, 212, 255);")
        self.nextButton.setObjectName("nextButton")
        self.finishButton = QtWidgets.QPushButton(self.centralwidget)
        self.finishButton.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.finishButton.setStyleSheet("font: 8pt \"Segoe Script\";\n"
"color: rgb(144, 0, 216);\n"
"background-color: rgb(219, 212, 255);")
        self.finishButton.setObjectName("finishButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "Угадай город!"))
        self.label.setText(_translate("MainWindow", "Ваше предположение:"))
        self.answerButton.setText(_translate("MainWindow", "Ответить"))
        self.nextButton.setText(_translate("MainWindow", "->"))
        self.finishButton.setText(_translate("MainWindow", "Завершить игру"))
